version: '3.9'
services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ConnectionStrings__Default: "Host=${DB__POSTGRES_HOST};Port=${DB__POSTGRES_PORT};Database=${DB__POSTGRES_DB};Username=${DB__POSTGRES_USER};Password=${DB__POSTGRES_PASSWORD}"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
      
  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB__POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DB__POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${DB__POSTGRES_DB:-postgres}
    ports:
      - "${DB__POSTGRES_PORT:-5432}:${DB__POSTGRES_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
volumes:
  pgdata: